# Generated by Django 4.0.3 on 2022-04-05 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menulist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menuId', models.CharField(max_length=50)),
                ('menuName', models.CharField(max_length=200)),
                ('menuCreateDate', models.DateTimeField()),
                ('menuUse', models.CharField(max_length=10)),
                ('menuNote', models.TextField()),
            ],
        ),
    ]
